project_id = "ncmsevbojzotkkfgoabp"

[functions.b3ta-ai-consultant]
verify_jwt = false

[functions.save-lead]
verify_jwt = false

[functions.ai-lead-scorer]
verify_jwt = true

[functions.create-quotation-payment-link]
verify_jwt = true

[functions.send-quotation-email]
verify_jwt = true

[functions.improve-report-text]
verify_jwt = true

[functions.send-meeting-reminder]
verify_jwt = false

[functions.send-email]
verify_jwt = true

[functions.sync-emails]
verify_jwt = true

[functions.improve-email-text]
verify_jwt = true

[functions.receive-email-webhook]
verify_jwt = false

[functions.poll-emails-imap]
verify_jwt = true