project_id = "ncmsevbojzotkkfgoabp"

[functions.b3ta-ai-consultant]
verify_jwt = false

[functions.save-lead]
verify_jwt = false

[functions.ai-lead-scorer]
verify_jwt = true

[functions.create-quotation-payment-link]
verify_jwt = true

[functions.send-quotation-email]
verify_jwt = true

[functions.generate-quotation-pdf]
verify_jwt = true